hostPort: 127.0.0.1:1099
username:
password:
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1099/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
  - pattern: ".*"